-- ============================================================================
--  Obuna aqli: foizli limitlar, pay-as-you-go va bepul zaxira model
--
--  Foydalanuvchiga token soni koʻrsatilmaydi. U «haftalik limitning 64% i
--  qoldi» degan tushunarli raqamni koʻradi. Limit tugaganda ish toʻxtamaydi:
--  yoki hisobidagi puldan yechiladi (pay-as-you-go), yoki bepul, lekin
--  sekinroq «Daho Daily» modeliga oʻtadi.
-- ============================================================================

-- ---------------------------------------------------------------------------
--  1. Rejaga oyna-limitlari
-- ---------------------------------------------------------------------------
alter table public.plans
  add column if not exists hourly_credit_cap  numeric(14, 2),
  add column if not exists weekly_credit_cap  numeric(14, 2),
  -- Limit tugaganda nima boʻladi
  add column if not exists allow_payg         boolean not null default true,
  add column if not exists daily_model_access text not null default 'limited'
    check (daily_model_access in ('none', 'limited', 'unlimited')),
  -- Bepul zaxira modeldan kuniga nechta xabar (limited uchun)
  add column if not exists daily_model_quota  integer not null default 30;

comment on column public.plans.hourly_credit_cap is
  'Soatiga sarflanadigan kredit chegarasi. null — cheklovsiz.';
comment on column public.plans.daily_model_access is
  'Limit tugagach bepul «Daho Daily» modeli: yoʻq / cheklangan / cheksiz.';

-- ---------------------------------------------------------------------------
--  2. Hisobdagi pul — pay-as-you-go uchun
--
--  Kredit (obuna bilan beriladi, har davrda kuyadi) va pul (foydalanuvchi
--  toʻlagan, kuymaydi) — bu ikki xil narsa, shuning uchun alohida turadi.
-- ---------------------------------------------------------------------------
alter table public.credit_balances
  add column if not exists wallet numeric(14, 2) not null default 0;

comment on column public.credit_balances.wallet is
  'Pay-as-you-go hamyoni. Obuna krediti tugagach shundan yechiladi; '
  'davr almashganda kuymaydi.';

create table if not exists public.wallet_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(14, 2) not null,          -- + toʻldirish, − sarf
  reason text not null default '',
  admin_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists wallet_events_user_idx
  on public.wallet_events(user_id, created_at desc);

alter table public.wallet_events enable row level security;

drop policy if exists wallet_events_read on public.wallet_events;
create policy wallet_events_read on public.wallet_events
  for select using (user_id = auth.uid() or public.is_admin());

-- ---------------------------------------------------------------------------
--  3. Bepul zaxira modeldan foydalanish hisobi
-- ---------------------------------------------------------------------------
create table if not exists public.daily_model_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null default current_date,
  calls integer not null default 0,
  primary key (user_id, day)
);

alter table public.daily_model_usage enable row level security;

drop policy if exists daily_usage_read on public.daily_model_usage;
create policy daily_usage_read on public.daily_model_usage
  for select using (user_id = auth.uid() or public.is_admin());

-- ---------------------------------------------------------------------------
--  4. Oynalar boʻyicha sarf — foizli koʻrsatkich uchun
-- ---------------------------------------------------------------------------

-- Bitta oynaning holati. Chegara yoʻq boʻlsa — cheksiz.
create or replace function public.window_state(p_used numeric, p_cap numeric)
returns jsonb language sql immutable as $$
  select case
    when p_cap is null or p_cap <= 0 then
      jsonb_build_object('unlimited', true, 'left_percent', 100)
    else jsonb_build_object(
      'unlimited', false,
      'left_percent', greatest(0, least(100,
        round((1 - coalesce(p_used, 0) / p_cap) * 100)::int
      ))
    )
  end;
$$;

create or replace function public.usage_windows(p_user uuid default auth.uid())
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_plan public.plans%rowtype;
  v_bal public.credit_balances%rowtype;
  v_hour numeric;
  v_day numeric;
  v_week numeric;
  v_daily_calls integer;
begin
  v_plan := public.active_plan(p_user);
  select * into v_bal from public.credit_balances where user_id = p_user;

  select coalesce(sum(credits), 0) into v_hour from public.usage_events
   where user_id = p_user and created_at >= now() - interval '1 hour';
  select coalesce(sum(credits), 0) into v_day from public.usage_events
   where user_id = p_user and created_at >= date_trunc('day', now());
  select coalesce(sum(credits), 0) into v_week from public.usage_events
   where user_id = p_user and created_at >= date_trunc('week', now());

  select coalesce(calls, 0) into v_daily_calls
    from public.daily_model_usage
   where user_id = p_user and day = current_date;

  return jsonb_build_object(
    'plan',   v_plan.code,
    -- Har bir oyna: sarflangan, chegara va QOLGAN FOIZ.
    'hour',   public.window_state(v_hour, v_plan.hourly_credit_cap),
    'day',    public.window_state(v_day,  v_plan.daily_credit_cap),
    'week',   public.window_state(v_week, v_plan.weekly_credit_cap),
    'period', public.window_state(
                coalesce(v_bal.granted, 0) - coalesce(v_bal.balance, 0),
                nullif(coalesce(v_bal.granted, 0), 0)
              ),
    'wallet',       coalesce(v_bal.wallet, 0),
    'allow_payg',   coalesce(v_plan.allow_payg, true),
    'daily_model',  jsonb_build_object(
      'access', coalesce(v_plan.daily_model_access, 'limited'),
      'used',   coalesce(v_daily_calls, 0),
      'quota',  coalesce(v_plan.daily_model_quota, 30)
    ),
    'period_end', v_bal.period_end
  );
end;
$$;

grant execute on function public.usage_windows(uuid) to authenticated;
grant execute on function public.window_state(numeric, numeric) to authenticated;
