-- ============================================================================
--  Daho — obuna, tariflar, Daho modellari va token hisobi
--  Bu migratsiya loyihani "har kim oʻz API kalitini qoʻyadi" modelidan
--  "Daho hisobi + obuna" modeliga oʻtkazadi.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
--  Tariflar
-- ---------------------------------------------------------------------------
create table if not exists public.plans (
  id           uuid primary key default gen_random_uuid(),
  code         text not null unique,              -- 'free', 'start', 'pro', 'max'
  name         text not null,                     -- "Bepul", "Pro"
  tagline      text not null default '',
  rank         int  not null default 0,           -- 0 = bepul; katta = kuchli
  price_uzs    bigint not null default 0,         -- oyiga, soʻmda
  monthly_tokens bigint not null default 0,       -- oylik token chegarasi
  daily_messages int not null default 0,          -- 0 = cheksiz
  features     jsonb not null default '[]'::jsonb,
  active       bool not null default true,
  created_at   timestamptz not null default now()
);

comment on column public.plans.rank is
  'Tarif darajasi. Model min_rank <= foydalanuvchi rank boʻlsa ochiq.';

-- ---------------------------------------------------------------------------
--  Foydalanuvchi profili
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         text not null default '',
  full_name     text not null default '',
  role          text not null default 'user' check (role in ('user', 'admin')),
  plan_code     text not null default 'free' references public.plans(code),
  plan_expires_at timestamptz,
  tokens_used   bigint not null default 0,
  period_start  timestamptz not null default date_trunc('month', now()),
  blocked       bool not null default false,
  note          text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists profiles_plan_idx on public.profiles(plan_code);

-- ---------------------------------------------------------------------------
--  Daho modellari — nom foydalanuvchiga, upstream faqat serverga
-- ---------------------------------------------------------------------------
create table if not exists public.daho_models (
  id           uuid primary key default gen_random_uuid(),
  slug         text not null unique,              -- 'dahox'
  name         text not null,                     -- 'DahoX'
  tagline      text not null default '',
  upstream_ref text not null,                     -- 'qwen/qwen3-max'  (SIR)
  upstream     text not null default 'openrouter',
  min_rank     int  not null default 0,           -- 0 = bepul foydalanuvchiga ham
  token_multiplier numeric not null default 1,    -- 1 token = necha "Daho token"
  context_tokens int not null default 32000,
  vision       bool not null default false,
  tools        bool not null default true,
  images       bool not null default false,
  sort         int  not null default 100,
  active       bool not null default true,
  created_at   timestamptz not null default now()
);

comment on column public.daho_models.upstream_ref is
  'Haqiqiy model nomi (OpenRouter). Foydalanuvchiga HECH QACHON koʻrsatilmaydi.';

-- ---------------------------------------------------------------------------
--  Sarf hisobi
-- ---------------------------------------------------------------------------
create table if not exists public.usage_events (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  model_slug   text not null default '',
  prompt_tokens int not null default 0,
  completion_tokens int not null default 0,
  billed_tokens int not null default 0,
  kind         text not null default 'chat',
  created_at   timestamptz not null default now()
);

create index if not exists usage_user_time_idx on public.usage_events(user_id, created_at desc);

-- ---------------------------------------------------------------------------
--  Obuna soʻrovlari — toʻlov admin bilan aloqada
-- ---------------------------------------------------------------------------
create table if not exists public.subscription_requests (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  plan_code    text not null references public.plans(code),
  months       int not null default 1,
  status       text not null default 'pending' check (status in ('pending','approved','rejected')),
  contact      text not null default '',
  message      text not null default '',
  admin_note   text not null default '',
  created_at   timestamptz not null default now(),
  decided_at   timestamptz,
  decided_by   uuid references auth.users(id)
);

create index if not exists subreq_status_idx on public.subscription_requests(status, created_at desc);

-- ---------------------------------------------------------------------------
--  Suhbatlar — qurilmalar orasida sinxron
-- ---------------------------------------------------------------------------
create table if not exists public.chats (
  id           uuid primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  title        text not null default '',
  model        text not null default '',
  messages     jsonb not null default '[]'::jsonb,
  source       text not null default 'app',       -- app | web | extension
  deleted      bool not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists chats_user_time_idx on public.chats(user_id, updated_at desc);

-- ---------------------------------------------------------------------------
--  Umumiy sozlamalar (aloqa maʼlumotlari, yuklab olish havolalari)
-- ---------------------------------------------------------------------------
create table if not exists public.app_settings (
  key   text primary key,
  value jsonb not null default '{}'::jsonb
);

-- ============================================================================
--  Yordamchi funksiyalar
-- ============================================================================

-- Joriy foydalanuvchi admin mi. RLS ichida ishlatilgani uchun
-- security definer — aks holda profiles ustidagi siyosat oʻzini chaqirib
-- cheksiz rekursiyaga tushadi.
create or replace function public.is_admin()
returns bool
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select p.role = 'admin' from public.profiles p where p.id = auth.uid()),
    false
  );
$$;

-- Foydalanuvchining amaldagi tarif darajasi.
-- Muddati oʻtgan obuna avtomatik bepulga tushadi.
create or replace function public.plan_rank_of(uid uuid)
returns int
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select case
               when p.plan_expires_at is not null and p.plan_expires_at < now() then 0
               else coalesce(pl.rank, 0)
             end
      from public.profiles p
      left join public.plans pl on pl.code = p.plan_code
      where p.id = uid
    ),
    0
  );
$$;

-- Yangi foydalanuvchi roʻyxatdan oʻtganda profil ochiladi.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owners jsonb;
  is_owner bool := false;
begin
  -- Egasining pochtasi app_settings da turadi: u roʻyxatdan oʻtishi bilan
  -- avtomatik admin boʻladi, SQL ni qoʻlda yozish shart emas.
  select value into owners from public.app_settings where key = 'owner_emails';
  if owners is not null then
    is_owner := exists (
      select 1 from jsonb_array_elements_text(owners) e
      where lower(e) = lower(coalesce(new.email, ''))
    );
  end if;

  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case when is_owner then 'admin' else 'user' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- updated_at ni oʻzi yangilaydi.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists chats_touch on public.chats;
create trigger chats_touch before update on public.chats
  for each row execute function public.touch_updated_at();

-- Oylik kvota holati. Oy almashgan boʻlsa hisob nolga tushgan deb koʻrsatiladi
-- (haqiqiy nolga tushirishni AI proxy yozuv paytida bajaradi).
create or replace function public.quota_state()
returns table (
  plan_code text,
  plan_name text,
  plan_rank int,
  monthly_tokens bigint,
  tokens_used bigint,
  tokens_left bigint,
  period_start timestamptz,
  resets_at timestamptz,
  plan_expires_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.plan_code,
    coalesce(pl.name, 'Bepul'),
    public.plan_rank_of(p.id),
    coalesce(pl.monthly_tokens, 0),
    case when p.period_start < date_trunc('month', now()) then 0 else p.tokens_used end,
    greatest(
      coalesce(pl.monthly_tokens, 0)
        - case when p.period_start < date_trunc('month', now()) then 0 else p.tokens_used end,
      0
    ),
    p.period_start,
    date_trunc('month', now()) + interval '1 month',
    p.plan_expires_at
  from public.profiles p
  left join public.plans pl on pl.code = p.plan_code
  where p.id = auth.uid();
$$;

-- ============================================================================
--  RLS — qatorlar himoyasi
-- ============================================================================

alter table public.plans                 enable row level security;
alter table public.profiles              enable row level security;
alter table public.daho_models           enable row level security;
alter table public.usage_events          enable row level security;
alter table public.subscription_requests enable row level security;
alter table public.chats                 enable row level security;
alter table public.app_settings          enable row level security;

-- Tariflar: hamma koʻradi, faqat admin oʻzgartiradi.
drop policy if exists plans_read on public.plans;
create policy plans_read on public.plans
  for select using (active or public.is_admin());

drop policy if exists plans_admin on public.plans;
create policy plans_admin on public.plans
  for all using (public.is_admin()) with check (public.is_admin());

-- Profil: oʻzini koʻradi va cheklangan maydonlarni oʻzgartiradi; admin hammasini.
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists profiles_admin on public.profiles;
create policy profiles_admin on public.profiles
  for all using (public.is_admin()) with check (public.is_admin());

-- Foydalanuvchi oʻz tarifini yoki rolini oʻzgartira olmaydi.
create or replace function public.guard_profile_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return new;
  end if;
  new.role            := old.role;
  new.plan_code       := old.plan_code;
  new.plan_expires_at := old.plan_expires_at;
  new.tokens_used     := old.tokens_used;
  new.period_start    := old.period_start;
  new.blocked         := old.blocked;
  return new;
end;
$$;

drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard before update on public.profiles
  for each row execute function public.guard_profile_update();

-- Modellar: asosiy jadval FAQAT admin uchun (upstream_ref sir).
drop policy if exists models_admin on public.daho_models;
create policy models_admin on public.daho_models
  for all using (public.is_admin()) with check (public.is_admin());

-- Foydalanuvchi modellarni shu koʻrinish orqali koʻradi — upstream_ref yoʻq.
-- Koʻrinish egasi huquqi bilan ishlaydi (security_invoker = off), shuning
-- uchun asosiy jadvaldagi "faqat admin" siyosati bu yerda toʻsiq boʻlmaydi.
drop view if exists public.models;
create view public.models
with (security_invoker = off)
as
  select
    m.slug,
    m.name,
    m.tagline,
    m.min_rank,
    m.context_tokens,
    m.vision,
    m.tools,
    m.images,
    m.sort,
    (m.min_rank > public.plan_rank_of(auth.uid())) as locked
  from public.daho_models m
  where m.active;

grant select on public.models to anon, authenticated;

-- Sarf: oʻzini koʻradi, admin hammasini. Yozishni faqat server (service_role) qiladi.
drop policy if exists usage_read on public.usage_events;
create policy usage_read on public.usage_events
  for select using (user_id = auth.uid() or public.is_admin());

-- Obuna soʻrovi: oʻzi yaratadi va koʻradi; admin hammasini boshqaradi.
drop policy if exists subreq_own on public.subscription_requests;
create policy subreq_own on public.subscription_requests
  for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists subreq_insert on public.subscription_requests;
create policy subreq_insert on public.subscription_requests
  for insert with check (user_id = auth.uid());

drop policy if exists subreq_admin on public.subscription_requests;
create policy subreq_admin on public.subscription_requests
  for all using (public.is_admin()) with check (public.is_admin());

-- Suhbatlar: faqat egasi.
drop policy if exists chats_own on public.chats;
create policy chats_own on public.chats
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Sozlamalar: hamma oʻqiydi, admin yozadi.
drop policy if exists settings_read on public.app_settings;
create policy settings_read on public.app_settings for select using (true);

drop policy if exists settings_admin on public.app_settings;
create policy settings_admin on public.app_settings
  for all using (public.is_admin()) with check (public.is_admin());

-- ============================================================================
--  Admin uchun koʻrsatkichlar
-- ============================================================================

create or replace function public.admin_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case when not public.is_admin() then '{}'::jsonb else jsonb_build_object(
    'users',        (select count(*) from public.profiles),
    'paid_users',   (select count(*) from public.profiles p
                       join public.plans pl on pl.code = p.plan_code
                      where pl.rank > 0
                        and (p.plan_expires_at is null or p.plan_expires_at > now())),
    'pending',      (select count(*) from public.subscription_requests where status = 'pending'),
    'tokens_month', (select coalesce(sum(billed_tokens), 0) from public.usage_events
                      where created_at >= date_trunc('month', now())),
    'tokens_today', (select coalesce(sum(billed_tokens), 0) from public.usage_events
                      where created_at >= date_trunc('day', now())),
    'top_models',   (select coalesce(jsonb_agg(t), '[]'::jsonb) from (
                        select model_slug as slug, sum(billed_tokens)::bigint as tokens
                          from public.usage_events
                         where created_at >= date_trunc('month', now())
                         group by model_slug order by 2 desc limit 8
                      ) t)
  ) end;
$$;

-- ============================================================================
--  Boshlangʻich maʼlumot
-- ============================================================================

insert into public.app_settings (key, value) values
  ('owner_emails', '["sarvarbeksanjarivich@gmail.com"]'::jsonb),
  ('contact', jsonb_build_object(
     'telegram', 'https://t.me/uzbleaderrr',
     'phone',    '',
     'email',    'sarvarbeksanjarivich@gmail.com'
   )),
  ('downloads', jsonb_build_object(
     'apk',       '',
     'extension', ''
   ))
on conflict (key) do nothing;

insert into public.plans (code, name, tagline, rank, price_uzs, monthly_tokens, daily_messages, features, active) values
  ('free',  'Bepul',  'Sinab koʻrish uchun',        0,       0,   200000, 30,
     '["Bepul Daho modellari","Oyiga 200 000 token","Kuniga 30 ta xabar","Suhbat tarixi sinxron"]'::jsonb, true),
  ('start', 'Start',  'Kundalik ish uchun',         1,   49000,  2000000, 0,
     '["Barcha oʻrta modellar","Oyiga 2 mln token","Cheksiz xabar","Kitob va konspekt","Fayl yuklash"]'::jsonb, true),
  ('pro',   'Pro',    'Kuchli modellar, koʻp ish',  2,  129000,  8000000, 0,
     '["Barcha modellar","Oyiga 8 mln token","Daho Code agenti","Rasm yaratish","Ustuvor navbat"]'::jsonb, true),
  ('max',   'Max',    'Cheklovsiz ishlash',         3,  299000, 30000000, 0,
     '["Hamma narsa Pro dan","Oyiga 30 mln token","Eng uzun kontekst","Yangi modellar birinchi","Toʻgʻridan-toʻgʻri yordam"]'::jsonb, true)
on conflict (code) do nothing;

-- Namunaviy Daho modellari. Admin panelda nomini ham, ichidagi modelni ham
-- istagancha oʻzgartirasiz — foydalanuvchi faqat Daho nomini koʻradi.
insert into public.daho_models
  (slug, name, tagline, upstream_ref, min_rank, token_multiplier, context_tokens, vision, tools, images, sort) values
  ('dahobro',   'DahoBro',   'Tez va bepul — kundalik savollar uchun',
      'meta-llama/llama-3.3-70b-instruct:free',  0, 1.0,  32000, false, false, false, 10),
  ('dahomini',  'DahoMini',  'Yengil, tez javob beradi',
      'qwen/qwen3-30b-a3b:free',                 0, 1.0,  32000, false, true,  false, 20),
  ('dahox',     'DahoX',     'Kundalik ish uchun kuchli model',
      'qwen/qwen3-coder',                        1, 1.5, 128000, false, true,  false, 30),
  ('dahonator', 'Dahonator', 'Eng kuchli — murakkab reja va tahlil',
      'qwen/qwen3-max',                          2, 3.0, 256000, true,  true,  false, 40),
  ('dahovision','DahoVision','Rasmni koʻradi va tushuntiradi',
      'qwen/qwen2.5-vl-72b-instruct',            2, 2.0,  32000, true,  false, false, 50),
  ('dahoart',   'DahoArt',   'Rasm va muqova yaratadi',
      'google/gemini-2.5-flash-image-preview',   2, 4.0,  32000, false, false, true,  60)
on conflict (slug) do nothing;
